/** Columnas alineadas con exportación Screaming Frog (CSV de referencia). */
export const SCANNER_COLUMNS = [
  'Dirección',
  'Tipo de contenido',
  'Código de respuesta',
  'Respuesta',
  'Indexabilidad',
  'Estado de indexabilidad',
  'Título 1',
  'Longitud del título 1',
  'Ancho de píxeles del título 1',
  'Meta description 1',
  'Longitud de la meta description 1',
  'Ancho de píxeles de la meta description 1',
  'Meta Keywords 1',
  'Longitud de meta keywords 1',
  'H1-1',
  'Longitud de H1-1',
  'H2-1',
  'Longitud de H2-1',
  'H2-2',
  'Longitud de H2-2',
  'Meta robots 1',
  'X-Robots-Tag 1',
  'Meta Refresh 1',
  'Elemento de enlace canónico 1',
  'rel="next" 1',
  'rel="prev" 1',
  'HTTP rel="next" 1',
  'HTTP rel="prev" 1',
  'Elemento de enlace amphtml',
  'Tamaño (bytes)',
  'Transferido (bytes)',
  'Total transferido (bytes)',
  'CO2 (mg)',
  'Clasificación de huella de carbono',
  'Recuento de palabras',
  'Número de oraciones',
  'Media de palabras por oración',
  'Puntuación de facilidad de lectura de Flesch',
  'Lectura',
  'Proporción de texto',
  'Nivel de profundidad',
  'Profundidad de carpeta',
  'Link Score',
  'Enlaces internos',
  'Enlaces internos únicos',
  'Enlaces JS únicos',
  '% del total',
  'Enlaces salientes',
  'Enlaces salientes únicos',
  'Enlaces salientes JS únicos',
  'Enlaces salientes externos',
  'Enlaces salientes externos únicos',
  'Enlaces salientes JS externos únicos',
  'Coincidencia casi duplicada más cercana',
  'Semiduplicados (N.º)',
  'Errores ortográficos',
  'Errores gramaticales',
  'Hash',
  'Tiempo de respuesta',
  'Last Modified',
  'URL de redirección',
  'Tipo de redirección',
  'Cookies',
  'Language',
  'Versión HTTP',
  'Enlace alternativo móvil',
  'Dirección semánticamente similar más cercana',
  'Puntuación de similitud semántica',
  'N.º semánticamente similares',
  'Puntuación de relevancia semántica',
  'Dirección codificada de URL',
  'Marca temporal del rastreo',
]
