/** Tipos populares (referencia estilo Schema Builder). */
export const POPULAR_SCHEMA_TYPES = [
  { key: 'Organization', label: 'Logo (Organization)' },
  { key: 'WebSite', label: 'WebSite' },
  { key: 'BreadcrumbList', label: 'Breadcrumb' },
  { key: 'AboutPage', label: 'About Page' },
  { key: 'ContactPage', label: 'Contact Page' },
  { key: 'FAQPage', label: 'FAQ Page' },
  { key: 'Article', label: 'Article' },
  { key: 'Product', label: 'Product' },
  { key: 'LocalBusiness', label: 'Local Business' },
  { key: 'Person', label: 'Person' },
  { key: 'VideoObject', label: 'Video' },
  { key: 'Event', label: 'Event' },
  { key: 'HowTo', label: 'HowTo' },
  { key: 'Recipe', label: 'Recipe' },
  { key: 'Review', label: 'Review' },
]

/** Catálogo amplio para lista “todos los soportados” (referencia UI). */
export const ALL_SCHEMA_TYPES = [
  'AboutPage',
  'AggregateRating',
  'Article',
  'BreadcrumbList',
  'Carousel',
  'ContactPage',
  'Course',
  'Dataset',
  'DiscussionForumPosting',
  'EmployerAggregateRating',
  'Event',
  'FAQPage',
  'HowTo',
  'ImageObject',
  'ItemList',
  'JobPosting',
  'LocalBusiness',
  'Movie',
  'Organization',
  'Person',
  'Product',
  'ProfilePage',
  'QAPage',
  'Recipe',
  'Review',
  'SoftwareApplication',
  'SpeakableSpecification',
  'TVSeries',
  'VideoObject',
  'WebPage',
  'WebSite',
  'MedicalWebPage',
  'CollectionPage',
  'SearchAction',
  'SiteNavigationElement',
  'Offer',
]
